// Import the functions you need from the SDKs you need
import { initializeApp } from 'firebase/app'
import { getFirestore, collection, getDocs, addDoc } from 'firebase/firestore'
// import { getAnalytics } from 'firebase/analytics'

// Import web app's Firebase configuration
import firebaseConfig from './firebaseConfig.js'

// Initialize Firebase
const app = initializeApp(firebaseConfig)

// Initialize Cloud Firestore and get a reference to the service
const db = getFirestore(app)

// Function to fetch feedbacks from Firebase
async function fetchFeedbacks () {
  const querySnapshot = await getDocs(collection(db, 'feedbacks'))
  const feedbacks = []
  querySnapshot.forEach((doc) => {
    feedbacks.push(doc.data())
  })
  return feedbacks
}

// Function to add a new feedback to Firebase
async function addFeedback (feedback) {
  // Add a new document to the "feedbacks" collection
  const docRef = await addDoc(collection(db, 'feedbacks'), feedback)
  console.log('ID autogenerated by Firebase:', docRef.id)

  return docRef.id // Return the ID of the newly added feedback
}

export {
  db, // main db interconnection reference
  fetchFeedbacks,
  addFeedback
}
